// <auto-generated />
using System;
using HospitalSurgical.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HospitalSurgical.Infrastructure.Migrations
{
    [DbContext(typeof(SurgicalDbContext))]
    [Migration("20260304171015_Step4_SoftDelete_IsDeleted")]
    partial class Step4_SoftDelete_IsDeleted
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("HospitalSurgical.Domain.Entities.OperatingRoom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Equipment")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Floor")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoomNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_OperatingRoom_Number");

                    b.ToTable("OperatingRooms", (string)null);
                });

            modelBuilder.Entity("HospitalSurgical.Domain.Entities.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CreatedBy")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("System");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("UpdatedBy")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("System");

                    b.HasKey("Id");

                    b.HasIndex("FileNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_Patient_FileNumber");

                    b.ToTable("Patients", (string)null);
                });

            modelBuilder.Entity("HospitalSurgical.Domain.Entities.Staff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CreatedBy")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("System");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("StaffType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("UpdatedBy")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("System");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Staff_IsActive");

                    b.ToTable("Staff", (string)null);

                    b.HasDiscriminator<string>("StaffType").HasValue("Staff");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("HospitalSurgical.Domain.Entities.Surgery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CreatedBy")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("System");

                    b.Property<int>("EstimatedDurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("OperatingRoomId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PlannedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProcedureName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("SurgeonId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("UpdatedBy")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("System");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.HasIndex("PlannedDate")
                        .HasDatabaseName("IX_Surgery_PlannedDate");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Surgery_Status");

                    b.HasIndex("OperatingRoomId", "PlannedDate")
                        .HasDatabaseName("IX_Surgery_Room_Date");

                    b.HasIndex("SurgeonId", "PlannedDate")
                        .HasDatabaseName("IX_Surgery_Surgeon_Date");

                    b.ToTable("Surgeries", (string)null);
                });

            modelBuilder.Entity("HospitalSurgical.Domain.Entities.SurgeryNurse", b =>
                {
                    b.Property<int>("SurgeryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NurseId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsScrubNurse")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RoleDuringSurgery")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("SurgeryId", "NurseId");

                    b.HasIndex("NurseId");

                    b.ToTable("SurgeryNurses", (string)null);
                });

            modelBuilder.Entity("HospitalSurgical.Domain.Entities.AdministrativeStaff", b =>
                {
                    b.HasBaseType("HospitalSurgical.Domain.Entities.Staff");

                    b.Property<string>("Function")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("OfficeNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Administrative");
                });

            modelBuilder.Entity("HospitalSurgical.Domain.Entities.Nurse", b =>
                {
                    b.HasBaseType("HospitalSurgical.Domain.Entities.Staff");

                    b.Property<string>("CertificationLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("CertificationLevel");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("DepartmentId");

                    b.Property<string>("ShiftPreference")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("ShiftPreference");

                    b.HasIndex("CertificationLevel")
                        .HasDatabaseName("IX_Nurse_CertificationLevel");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("IX_Nurse_DepartmentId")
                        .HasFilter("[DepartmentId] IS NOT NULL");

                    b.HasIndex("ShiftPreference", "IsActive")
                        .HasDatabaseName("IX_Nurse_Shift_Active");

                    b.HasDiscriminator().HasValue("Nurse");
                });

            modelBuilder.Entity("HospitalSurgical.Domain.Entities.Surgeon", b =>
                {
                    b.HasBaseType("HospitalSurgical.Domain.Entities.Staff");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("LicenseNumber");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("Specialty");

                    b.Property<int>("YearsOfExperience")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("YearsOfExperience");

                    b.HasIndex("LicenseNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_Surgeon_LicenseNumber");

                    b.HasIndex("Specialty")
                        .HasDatabaseName("IX_Surgeon_Specialty");

                    b.HasIndex("YearsOfExperience")
                        .HasDatabaseName("IX_Surgeon_YearsOfExperience");

                    b.HasIndex("Specialty", "IsActive")
                        .HasDatabaseName("IX_Surgeon_Specialty_Active");

                    b.HasDiscriminator().HasValue("Surgeon");
                });

            modelBuilder.Entity("HospitalSurgical.Domain.Entities.OperatingRoom", b =>
                {
                    b.OwnsOne("HospitalSurgical.Domain.ValueObjects.ContactInfo", "ContactInfo", b1 =>
                        {
                            b1.Property<int>("OperatingRoomId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("TEXT")
                                .HasColumnName("Email");

                            b1.Property<string>("EmergencyContact")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("TEXT")
                                .HasColumnName("EmergencyContact");

                            b1.Property<string>("EmergencyPhone")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("TEXT")
                                .HasColumnName("EmergencyPhone");

                            b1.Property<string>("Phone")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("TEXT")
                                .HasColumnName("Phone");

                            b1.HasKey("OperatingRoomId");

                            b1.ToTable("OperatingRooms");

                            b1.WithOwner()
                                .HasForeignKey("OperatingRoomId");
                        });

                    b.Navigation("ContactInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("HospitalSurgical.Domain.Entities.Patient", b =>
                {
                    b.OwnsOne("HospitalSurgical.Domain.ValueObjects.ContactInfo", "ContactInfo", b1 =>
                        {
                            b1.Property<int>("PatientId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("TEXT")
                                .HasColumnName("Email");

                            b1.Property<string>("EmergencyContact")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("TEXT")
                                .HasColumnName("EmergencyContact");

                            b1.Property<string>("EmergencyPhone")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("TEXT")
                                .HasColumnName("EmergencyPhone");

                            b1.Property<string>("Phone")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("TEXT")
                                .HasColumnName("Phone");

                            b1.HasKey("PatientId");

                            b1.ToTable("Patients");

                            b1.WithOwner()
                                .HasForeignKey("PatientId");
                        });

                    b.OwnsOne("HospitalSurgical.Domain.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<int>("PatientId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("Address_City");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("Address_Country");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("TEXT")
                                .HasColumnName("Address_Street");

                            b1.Property<string>("ZipCode")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("TEXT")
                                .HasColumnName("Address_ZipCode");

                            b1.HasKey("PatientId");

                            b1.ToTable("Patients");

                            b1.WithOwner()
                                .HasForeignKey("PatientId");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("ContactInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("HospitalSurgical.Domain.Entities.Surgery", b =>
                {
                    b.HasOne("HospitalSurgical.Domain.Entities.OperatingRoom", "OperatingRoom")
                        .WithMany("Surgeries")
                        .HasForeignKey("OperatingRoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HospitalSurgical.Domain.Entities.Patient", "Patient")
                        .WithMany("Surgeries")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HospitalSurgical.Domain.Entities.Surgeon", "Surgeon")
                        .WithMany("Surgeries")
                        .HasForeignKey("SurgeonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OperatingRoom");

                    b.Navigation("Patient");

                    b.Navigation("Surgeon");
                });

            modelBuilder.Entity("HospitalSurgical.Domain.Entities.SurgeryNurse", b =>
                {
                    b.HasOne("HospitalSurgical.Domain.Entities.Nurse", "Nurse")
                        .WithMany("SurgeryAssignments")
                        .HasForeignKey("NurseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HospitalSurgical.Domain.Entities.Surgery", "Surgery")
                        .WithMany("NurseAssignments")
                        .HasForeignKey("SurgeryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nurse");

                    b.Navigation("Surgery");
                });

            modelBuilder.Entity("HospitalSurgical.Domain.Entities.OperatingRoom", b =>
                {
                    b.Navigation("Surgeries");
                });

            modelBuilder.Entity("HospitalSurgical.Domain.Entities.Patient", b =>
                {
                    b.Navigation("Surgeries");
                });

            modelBuilder.Entity("HospitalSurgical.Domain.Entities.Surgery", b =>
                {
                    b.Navigation("NurseAssignments");
                });

            modelBuilder.Entity("HospitalSurgical.Domain.Entities.Nurse", b =>
                {
                    b.Navigation("SurgeryAssignments");
                });

            modelBuilder.Entity("HospitalSurgical.Domain.Entities.Surgeon", b =>
                {
                    b.Navigation("Surgeries");
                });
#pragma warning restore 612, 618
        }
    }
}
